Add drag and drop component
BartusZak/Solution pull request #138
Opened 2019-01-09 12:44 UTC by polubis

2019-01-09 12:53 UTC, mateusz14 requested changes
Missing "Too many files dropped" alert translation

2019-01-09 13:27 UTC, Reynart01 approved these changes

2019-01-10 12:31 UTC, BartusZak approved these changes

2019-01-10 12:31 UTC, BartusZak commented on src/components/common/drag-and-drop/drag-and-drop.js
> +
+1

2019-01-10 12:31 UTC, BartusZak commented on src/components/common/drag-and-drop/drag-and-drop.scss
> +@import '../../../scss/new-color-schema.scss';
add 1 line

2019-01-10 12:45 UTC, merged