Feature/confirm fancy modals
BartusZak/Solution pull request #163
Opened 2019-01-28 14:11 UTC by mateusz14

2019-01-28 14:12 UTC, polubis commented on src/components/common/confimModal/confirmModal.js
>      key={2}
Not needed key

2019-01-28 14:12 UTC, polubis commented on src/components/common/confimModal/confirmModal.js
>                  <button className="option-btn green-btn" onClick={operation}>{operationName}</button>
We have already implemented Button component which exists in common folder

2019-01-29 08:13 UTC, BartusZak requested changes

2019-01-29 08:13 UTC, BartusZak commented on src/components/common/modals/Confirmation.js
> +)(translate("Confirmation")(Confirmation));
Wrong syntax.
Change to translate("Confirmation")(connect(mapStateToProps,mapDispatchToProps)(Confirmation))

2019-01-29 08:20 UTC, BartusZak approved these changes

2019-01-29 08:20 UTC, merged